# -*- coding: utf-8 -*-
"""Ticketmachine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAL9TL6TDitSpqsw9YE7nXCasEyA44ho
"""

ticketoption = {
    1:{"name": "Bus","price": 10},
    2:{"name": "Train","price": 20},
    3:{"name": "BTS","price": 40},
    4:{"name": "Movie","price": 60},
    5:{"name": "Event","price": 75}
}

accepted_money = [1,5,10,20,50,100]
current_balance = 0

def show_ticketoption():
  print("\nticket option")
  for code, item in ticketoption.items():
    print(f"{code}. {item['name']} - {item['price']} THB")
def insert_money():
  global current_balance
  while True:
    money = int(input("Insert money(1,5,10,20,50,100)or 0 to stop"))
    if money == 0:
      break
    elif money in accepted_money:
      current_balance += money
      print(f"current balnce: {current_balance} THB")
    else:
      print ( "Invalid Money")
def select_ticket():
  global current_balance
  choice = int(input("Select ticket"))
  if choice not in ticketoption:
    print("Invalid choice")
    return
  ticket = ticketoption[choice]
  price = ticket["price"]
  if current_balance>=price:
    current_balance-=price
    print(f"\nPrinting {ticket['name']} ticket")
    print(f"\nChange returned{current_balance}THB")
    current_balance = 0
  else:
    print("Insufficient balance")
def vending_machine():
  print("Welcome to the ticket vending machine!")
  show_ticketoption()
  insert_money()
  select_ticket()
  print("Thank you for using our ticket vending machine!")

vending_machine()